/open Pair.java
/open Maybe.java
/open InfList.java
/open Course.java
/open Prereq.java
/open CourseReq.java
/open OneOf.java
/open AllOf.java
/open CoursePlan.java
/open SUstart.java
/open SUend.java
